# Generated by Django 3.0.7 on 2020-06-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_supplier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='porfile_pic',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_line1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_line2',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(default='', max_length=250),
        ),
    ]
