# Generated by Django 3.0.7 on 2020-06-22 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200622_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='pincode',
        ),
    ]
