# Generated by Django 3.0.7 on 2020-06-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_supplier_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
