# Generated by Django 3.0.7 on 2020-06-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200622_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='state',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
