# Generated by Django 3.0.7 on 2020-06-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200622_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payemnt_done',
            new_name='payment_done',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='total_payemnt',
            new_name='total_payment',
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
