# Generated by Django 3.0.7 on 2020-06-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200622_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='total_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10, null=True),
        ),
    ]
