# Generated by Django 3.0.7 on 2020-06-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200622_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
