# Generated by Django 3.0.7 on 2020-06-22 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_done',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator('0.00')]),
        ),
    ]
