# Generated by Django 3.0.7 on 2020-06-22 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200622_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_done',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
