# Generated by Django 3.0.7 on 2020-06-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200622_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='closing_balance',
            field=models.FloatField(default=0),
        ),
    ]
