# Generated by Django 3.0.7 on 2020-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Partial', 'Partial'), ('Complete', 'Complete'), ('Overdue', 'Overdue'), ('Advance', 'Advance')], default='Partial', max_length=250),
        ),
    ]
